package io.github.xis3794.mirrorbox.ui.screens

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.unit.dp
import io.github.xis3794.mirrorbox.core.Fmt
import io.github.xis3794.mirrorbox.nav.Navigator
import io.github.xis3794.mirrorbox.ops.BootRecords
import io.github.xis3794.mirrorbox.ops.EditOps
import io.github.xis3794.mirrorbox.ops.GrubBoot
import io.github.xis3794.mirrorbox.ops.PartitionOps
import io.github.xis3794.mirrorbox.qcow2.disk.Guid
import io.github.xis3794.mirrorbox.qcow2.disk.MbrType
import io.github.xis3794.mirrorbox.qcow2.disk.NewPartition
import io.github.xis3794.mirrorbox.qcow2.disk.PartitionEntry
import io.github.xis3794.mirrorbox.qcow2.disk.PartitionTableInfo
import io.github.xis3794.mirrorbox.ui.components.GlassSelectChip
import io.github.xis3794.mirrorbox.ui.components.InfoRow
import io.github.xis3794.mirrorbox.ui.components.ScreenHeader
import io.github.xis3794.mirrorbox.ui.glass.GlassButton
import io.github.xis3794.mirrorbox.ui.glass.GlassCard
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import java.io.File

/**
 * Partition editor: create, delete, activate and format partitions without a VM, root or loop
 * device. The table is regenerated by the pure Kotlin engine [PartitionOps]; filesystems are built
 * through the "safe track" (extract → mkfs → diff write-back), so only the touched clusters change.
 */
@Composable
fun PartitionEditorScreen(nav: Navigator, path: String) {
    val context = LocalContext.current
    val scope = rememberCoroutineScope()
    val file = remember(path) { File(path) }

    var table by remember { mutableStateOf<PartitionTableInfo?>(null) }
    var diskSize by remember { mutableStateOf(0L) }
    var scheme by remember { mutableStateOf("MBR") }
    var draft by remember { mutableStateOf(emptyList<NewPartition>()) }
    var freeSpaces by remember { mutableStateOf(emptyList<PartitionOps.FreeSpace>()) }
    var typeIndex by remember { mutableStateOf(0) }
    var startMib by remember { mutableStateOf("") }
    var sizeMib by remember { mutableStateOf("") }
    var formatIndex by remember { mutableStateOf(1) }
    var fsKind by remember { mutableStateOf(EditOps.FsKind.EXT4) }
    var label by remember { mutableStateOf("MIRRORBOX") }
    var bootPath by remember { mutableStateOf("") }
    var bootMessage by remember { mutableStateOf<String?>(null) }
    val grubReady = remember { GrubBoot.available(context) }
    val grubCoreKiB = remember { GrubBoot.coreSize(context) / 1024 }
    var status by remember { mutableStateOf<String?>(null) }
    var busy by remember { mutableStateOf(false) }

    fun refresh() {
        scope.launch {
            busy = true
            val snapshot = withContext(Dispatchers.IO) {
                val info = EditOps.detectPartitionTable(file)
                val size = runCatching { io.github.xis3794.mirrorbox.qcow2.Qcow2Image.open(file).use { it.virtualSize } }
                    .getOrDefault(0L)
                Triple(info, size, info?.partitions ?: emptyList())
            }
            val info = snapshot.first
            diskSize = snapshot.second
            table = info
            if (info != null && info.scheme != "none") scheme = info.scheme
            freeSpaces = if (info != null) PartitionOps.freeSpaces(diskSize, info) else emptyList()
            // Start from what is actually on disk; the user then edits the draft and applies it.
            draft = snapshot.third.map { it.toNew(scheme) }
            draft.firstOrNull()?.let { first ->
                formatIndex = 1
                startMib = (first.startLba / PartitionOps.ALIGN_SECTORS).toString()
                sizeMib = (first.sectorCount / PartitionOps.ALIGN_SECTORS).toString()
            }
            status = if (info?.scheme == "none" || info == null) {
                "磁盘上没有分区表：可以从「一键布局」开始"
            } else {
                null
            }
            busy = false
        }
    }

    LaunchedEffect(path) { refresh() }

    val choices = PartitionOps.typeChoices(scheme)
    val gpt = scheme.equals("GPT", ignoreCase = true)

    Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState())) {
        ScreenHeader(
            title = "分区编辑器",
            subtitle = "${file.name} · $scheme · ${Fmt.size(diskSize)}",
            onBack = { nav.pop() },
        )

        Column(Modifier.padding(horizontal = 20.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) {
            GlassCard(Modifier.fillMaxWidth()) {
                Text("磁盘", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.onSurface)
                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    GlassSelectChip("MBR", !gpt, { scheme = "MBR"; draft = emptyList(); typeIndex = 0 })
                    GlassSelectChip("GPT", gpt, { scheme = "GPT"; draft = emptyList(); typeIndex = 0 })
                }
                Spacer(Modifier.height(8.dp))
                InfoRow("当前分区表", table?.scheme ?: "无")
                InfoRow("磁盘容量", Fmt.size(diskSize))
                InfoRow("已用分区", "${draft.size} 个")
                Spacer(Modifier.height(10.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    GlassButton("一键布局") {
                        val layout = PartitionOps.suggestedLayout(diskSize, scheme)
                        if (layout.isEmpty()) {
                            status = "磁盘太小，无法创建分区"
                        } else {
                            draft = layout
                            status = "已生成建议布局：${layout.size} 个分区（尚未写入）"
                        }
                    }
                    GlassButton("重新读取", enabled = !busy) { refresh(); status = "已重新读取分区表" }
                }
                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    GlassButton("清除分区表", enabled = !busy) {
                        val result = PartitionOps.wipe(file)
                        refresh()
                        status = result.message
                    }
                    GlassButton("应用分区表", enabled = !busy && draft.isNotEmpty()) {
                        val result = PartitionOps.applyTable(file, scheme, draft)
                        refresh()
                        status = result.message
                    }
                }
                Spacer(Modifier.height(8.dp))
                GlassButton("释放 WIM 到分区", enabled = !busy, modifier = Modifier.fillMaxWidth()) {
                    nav.push(io.github.xis3794.mirrorbox.nav.Screen.WimRelease(file.absolutePath))
                    status = "已打开「释放 WIM」：可把 Windows 镜像展开并写入分区"
                }
                Spacer(Modifier.height(8.dp))
                GlassButton("客户机文件浏览", enabled = !busy, modifier = Modifier.fillMaxWidth()) {
                    nav.push(io.github.xis3794.mirrorbox.nav.Screen.GuestFiles(file.absolutePath))
                    status = "已打开「客户机文件」：浏览/复制分区内的文件"
                }
            }

            GlassCard(Modifier.fillMaxWidth()) {
                Text("分区（草稿）", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.onSurface)
                Spacer(Modifier.height(6.dp))
                Text(
                    "改动先只存在于草稿里，点「应用分区表」才会写入镜像；MBR 引导代码与磁盘签名会被保留。",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                Spacer(Modifier.height(8.dp))
                if (draft.isEmpty()) {
                    Text("尚无分区：用「一键布局」或下面的「新增分区」。",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
                draft.forEachIndexed { index, part ->
                    val typeName = if (gpt) Guid.typeNameFor(part.typeGuid) else MbrType.nameFor(part.typeId)
                    Column(Modifier.padding(vertical = 6.dp)) {
                        Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
                            Text(
                                "${index + 1}. ${part.name.ifBlank { typeName }}",
                                style = MaterialTheme.typography.bodyLarge,
                                color = MaterialTheme.colorScheme.onSurface,
                            )
                            Text(
                                Fmt.size(part.sectorCount * PartitionOps.SECTOR),
                                style = MaterialTheme.typography.bodyMedium,
                                color = MaterialTheme.colorScheme.primary,
                            )
                        }
                        Text(
                            "$typeName · 起始 LBA ${part.startLba}（${Fmt.size(part.startLba * PartitionOps.SECTOR)}）" +
                                if (part.bootable) " · 活动" else "",
                            style = MaterialTheme.typography.bodySmall,
                            color = MaterialTheme.colorScheme.onSurfaceVariant,
                        )
                        Spacer(Modifier.height(4.dp))
                        Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                            GlassButton("删除") {
                                draft = draft.filterIndexed { i, _ -> i != index }
                                status = "已从草稿中删除分区 ${index + 1}"
                            }
                            if (!gpt) {
                                GlassButton("设为活动") {
                                    if (index < 4) {
                                        draft = draft.mapIndexed { i, p -> p.copy(bootable = i == index) }
                                        status = "草稿中已把分区 ${index + 1} 设为活动"
                                    } else {
                                        status = "MBR 只有前 4 个分区可以设为活动"
                                    }
                                }
                            }
                        }
                    }
                }
            }

            GlassCard(Modifier.fillMaxWidth()) {
                Text("新增分区", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.onSurface)
                Spacer(Modifier.height(6.dp))
                if (freeSpaces.isEmpty()) {
                    Text("没有可用的空闲空间（先删除分区或扩大磁盘）。",
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant)
                } else {
                    Text("空闲区域（点选填入）", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                    Spacer(Modifier.height(4.dp))
                    freeSpaces.take(4).forEach { space ->
                        GlassButton(
                            text = "${Fmt.size(space.startByte)} 起 · ${Fmt.size(space.sizeBytes)}",
                        ) {
                            startMib = (space.startLba / PartitionOps.ALIGN_SECTORS).toString()
                            sizeMib = (space.sectorCount / PartitionOps.ALIGN_SECTORS).toString()
                            status = "已填入空闲区域 ${Fmt.size(space.startByte)} 起 ${Fmt.size(space.sizeBytes)}"
                        }
                        Spacer(Modifier.height(6.dp))
                    }
                }
                Spacer(Modifier.height(6.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    OutlinedTextField(
                        value = startMib,
                        onValueChange = { startMib = it.filter { c -> c.isDigit() }.take(9) },
                        singleLine = true,
                        label = { Text("起始 (MiB)") },
                        modifier = Modifier.weight(1f),
                    )
                    OutlinedTextField(
                        value = sizeMib,
                        onValueChange = { sizeMib = it.filter { c -> c.isDigit() }.take(9) },
                        singleLine = true,
                        label = { Text("大小 (MiB)") },
                        modifier = Modifier.weight(1f),
                    )
                }
                Spacer(Modifier.height(8.dp))
                Text("类型", style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.onSurfaceVariant)
                Spacer(Modifier.height(4.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    choices.take(4).forEachIndexed { index, choice ->
                        GlassSelectChip(choice.label, index == typeIndex, { typeIndex = index })
                    }
                }
                Spacer(Modifier.height(10.dp))
                GlassButton("添加到草稿", enabled = draft.size < if (gpt) 128 else 4) {
                    val startLba = (startMib.toLongOrNull() ?: 0L) * PartitionOps.ALIGN_SECTORS
                    val sectors = (sizeMib.toLongOrNull() ?: 0L) * PartitionOps.ALIGN_SECTORS
                    status = when {
                        sectors <= 0L -> "请先填写大小"
                        startLba <= 0L -> "请先填写起始位置"
                        startLba + sectors > diskSize / PartitionOps.SECTOR ->
                            "超出磁盘范围（磁盘共 ${diskSize / PartitionOps.SECTOR} 扇区）"
                        draft.any { it.startLba < startLba + sectors && startLba < it.endLba + 1 } ->
                            "与已有分区重叠"
                        else -> {
                            val choice = choices.getOrNull(typeIndex) ?: choices.first()
                            val mbrType = choice.id.removePrefix("0x").toIntOrNull(16) ?: 0x83
                            draft = draft + NewPartition(
                                startLba = startLba,
                                sectorCount = sectors,
                                typeId = mbrType,
                                bootable = false,
                                name = if (gpt) "Partition ${draft.size + 1}" else "",
                                typeGuid = if (gpt) choice.id else Guid.LINUX_FILESYSTEM,
                            )
                            freeSpaces = table?.let { PartitionOps.freeSpaces(diskSize, it) } ?: emptyList()
                            "已加入草稿（记得应用分区表）"
                        }
                    }
                }
            }

            GlassCard(Modifier.fillMaxWidth()) {
                Text("格式化分区", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.onSurface)
                Spacer(Modifier.height(6.dp))
                Text(
                    "mkfs 在临时 raw 副本上进行，随后只把变化的簇写回 qcow2；分区表必须先应用。",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    draft.forEachIndexed { index, _ ->
                        if (index < 6) {
                            GlassSelectChip("分区 ${index + 1}", formatIndex == index + 1, { formatIndex = index + 1 })
                        }
                    }
                }
                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(6.dp)) {
                    EditOps.FsKind.entries.forEach { kind ->
                        GlassSelectChip(kind.label, fsKind == kind, { fsKind = kind })
                    }
                }
                Spacer(Modifier.height(8.dp))
                OutlinedTextField(
                    value = label,
                    onValueChange = { label = it },
                    singleLine = true,
                    label = { Text("卷标") },
                    modifier = Modifier.fillMaxWidth(),
                )
                Spacer(Modifier.height(10.dp))
                GlassButton("格式化分区 $formatIndex", enabled = !busy && table?.partitions?.isNotEmpty() == true) {
                    val entry = table?.partitions?.firstOrNull { it.index == formatIndex }
                    if (entry == null) {
                        status = "找不到分区 $formatIndex：请先应用分区表并重新读取"
                    } else {
                        scope.launch {
                            busy = true
                            status = "正在格式化分区 $formatIndex …"
                            status = withContext(Dispatchers.IO) {
                                runCatching {
                                    PartitionOps.formatPartition(context, file, entry, fsKind, label).message
                                }.getOrElse { "格式化失败：${it.message}" }
                            }
                            busy = false
                        }
                    }
                }
            }

            GlassCard(Modifier.fillMaxWidth()) {
                Text("BIOS 引导", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.onSurface)
                Spacer(Modifier.height(6.dp))
                Text(
                    "内置 syslinux 引导记录，开箱即用（不需要自己准备 mbr.bin）。写入只覆盖 MBR 前 440 字节，" +
                        "分区表与 0x55AA 签名不变；若没有活动分区，会自动把第一个分区标记为活动。",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                Spacer(Modifier.height(8.dp))
                BootRecords.MBR_RECORDS.forEach { record ->
                    val present = BootRecords.available(context, record)
                    GlassButton(
                        text = if (present) {
                            "${record.title} · 写入（${record.sizeBytes} B）"
                        } else {
                            "${record.title}（APK 中缺失）"
                        },
                        modifier = Modifier.fillMaxWidth(),
                        enabled = present && !busy,
                    ) {
                        val result = BootRecords.install(context, file, record)
                        refresh()
                        val msg = "${result.message}（${record.title}）"
                        bootMessage = msg
                        status = msg
                        android.widget.Toast.makeText(context, msg, android.widget.Toast.LENGTH_SHORT).show()
                    }
                    Spacer(Modifier.height(4.dp))
                }
                InfoRow("当前磁盘推荐", BootRecords.recommended(scheme).title)

                Spacer(Modifier.height(12.dp))
                Text(
                    "真正可启动：GRUB（BIOS）",
                    style = MaterialTheme.typography.titleSmall,
                    color = MaterialTheme.colorScheme.onSurface,
                )
                Spacer(Modifier.height(4.dp))
                Text(
                    "syslinux 的 mbr.bin 只是“跳到活动分区的引导扇区”——分区里没有引导器时 BIOS 会直接报" +
                        "“no bootable device / 找不到硬盘”。GRUB 会把 core.img 写到 LBA 1 并在分区里放" +
                        " /boot/grub/grub.cfg（已用 QEMU/SeaBIOS 实测通过），SeaBIOS 下能直接进启动菜单。",
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.onSurfaceVariant,
                )
                Spacer(Modifier.height(8.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    GlassButton("安装 GRUB（BIOS）", enabled = !busy && grubReady) {
                        val msg = if (!grubReady) {
                            "APK 里没有 core.img（请重装完整包）"
                        } else {
                            GrubBoot.install(context, file).also { refresh() }.message
                        }
                        bootMessage = msg
                        status = msg
                        android.widget.Toast.makeText(context, msg, android.widget.Toast.LENGTH_LONG).show()
                    }
                    GlassButton("检查启动结构", enabled = !busy) {
                        val report = GrubBoot.diagnose(context, file).joinToString("\n")
                        bootMessage = report
                        status = "启动结构检查（详见 BIOS 引导卡片）"
                        android.widget.Toast.makeText(context, "启动结构检查完成", android.widget.Toast.LENGTH_SHORT).show()
                    }
                }
                Spacer(Modifier.height(4.dp))
                Text(
                    if (grubReady) {
                        "内置 GRUB core.img：${grubCoreKiB} KiB（写入 LBA 1，需要第一个分区起始 ≥ 2048）"
                    } else {
                        "未内置 GRUB 引导块：请安装包含 assets/grub 的完整 APK"
                    },
                    style = MaterialTheme.typography.bodySmall,
                    color = if (grubReady) MaterialTheme.colorScheme.onSurfaceVariant else MaterialTheme.colorScheme.error,
                )
                bootMessage?.let { msg ->
                    Spacer(Modifier.height(6.dp))
                    Text(
                        msg,
                        style = MaterialTheme.typography.bodyMedium,
                        color = if (msg.contains("失败") || msg.contains("不能")) {
                            MaterialTheme.colorScheme.error
                        } else {
                            MaterialTheme.colorScheme.tertiary
                        },
                    )
                }
                Spacer(Modifier.height(8.dp))
                OutlinedTextField(
                    value = bootPath,
                    onValueChange = { bootPath = it },
                    singleLine = true,
                    label = { Text("或填写自备引导记录（如 /sdcard/Download/mbr.bin）") },
                    modifier = Modifier.fillMaxWidth(),
                )
                Spacer(Modifier.height(10.dp))
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    GlassButton("写入自定义记录", enabled = !busy && bootPath.isNotBlank()) {
                        val blob = runCatching { File(bootPath.trim()).readBytes() }.getOrNull()
                        val msg = if (blob == null || blob.isEmpty()) {
                            "读不到引导记录：$bootPath"
                        } else {
                            PartitionOps.writeBootCode(file, blob).also { refresh() }.message
                        }
                        bootMessage = msg
                        status = msg
                        android.widget.Toast.makeText(context, msg, android.widget.Toast.LENGTH_SHORT).show()
                    }
                    GlassButton("查看当前引导代码", enabled = !busy) {
                        val code = PartitionOps.readBootCode(file)
                        val msg = if (code == null) {
                            "无法读取 MBR"
                        } else {
                            val nonZero = code.count { it.toInt() != 0 }
                            val hex = code.take(16).joinToString(" ") { "%02X".format(it) }
                            "前 16 字节：$hex （非零字节 $nonZero/440）"
                        }
                        bootMessage = msg
                        status = msg
                        android.widget.Toast.makeText(context, msg, android.widget.Toast.LENGTH_SHORT).show()
                    }
                }
            }

            if (status != null) {
                GlassCard(Modifier.fillMaxWidth()) {
                    Text("状态", style = MaterialTheme.typography.titleMedium, color = MaterialTheme.colorScheme.onSurface)
                    Spacer(Modifier.height(6.dp))
                    Text(status.orEmpty(), style = MaterialTheme.typography.bodyMedium, color = MaterialTheme.colorScheme.onSurfaceVariant)
                }
            }
            Spacer(Modifier.height(24.dp))
        }
    }
}

/** Maps a parsed entry back into an editable partition (used to seed the draft). */
private fun PartitionEntry.toNew(scheme: String): NewPartition {
    val gpt = scheme.equals("GPT", ignoreCase = true)
    val mbrType = typeId.removePrefix("0x").toIntOrNull(16) ?: 0x83
    return NewPartition(
        startLba = startLba,
        sectorCount = sectorCount,
        typeId = mbrType,
        bootable = bootable,
        name = name,
        typeGuid = if (gpt) typeId else Guid.LINUX_FILESYSTEM,
    )
}