package io.github.xis3794.mirrorbox.ops

import android.content.Context
import io.github.xis3794.mirrorbox.core.AppPaths
import io.github.xis3794.mirrorbox.core.Fmt
import io.github.xis3794.mirrorbox.qcow2.Qcow2Image
import io.github.xis3794.mirrorbox.qcow2.disk.Guid
import io.github.xis3794.mirrorbox.qcow2.disk.NewPartition
import io.github.xis3794.mirrorbox.qcow2.disk.PartitionEntry
import io.github.xis3794.mirrorbox.qcow2.disk.PartitionTableInfo
import io.github.xis3794.mirrorbox.qcow2.disk.PartitionTables
import io.github.xis3794.mirrorbox.qcow2.disk.SECTOR_SIZE
import java.io.File

/**
 * Partition level editing that never needs a VM, root or a loop device.
 *
 * All of it is byte math on the qcow2 through the built-in engine:
 *  - the table itself (MBR/GPT) is (re)generated by [PartitionTables]
 *  - a filesystem inside a partition is created through the existing "safe track": extract the
 *    partition into a raw file → mkfs with e2fsprogs / dosfstools / ntfsprogs → write back only the
 *    clusters that actually changed ([EditOps]) — the rest of the image is untouched
 *  - the MBR boot code area (bytes 0..439) can be written from any boot record blob (syslinux's
 *    `mbr.bin`, `isohdpfx.bin`, ms-sys, a GRUB stage1 …), which is what makes a disk image BIOS
 *    bootable without touching the partition table
 */
object PartitionOps {

    const val SECTOR = SECTOR_SIZE

    /** 1 MiB, the default alignment fdisk/parted use. */
    const val ALIGN_SECTORS = 2048L

    /** LBA 0..33 plus the backup header/entries at the end of the disk. */
    const val GPT_RESERVED_SECTORS = 2048L

    const val MIN_PARTITION_BYTES = 1024L * 1024L

    /** The 440 bytes of boot code that live in front of the MBR partition table. */
    const val BOOT_CODE_LENGTH = 440

    data class FreeSpace(val startLba: Long, val sectorCount: Long) {
        val startByte: Long get() = startLba * SECTOR
        val sizeBytes: Long get() = sectorCount * SECTOR
    }

    data class TypeChoice(val id: String, val label: String)

    data class PartitionResult(val ok: Boolean, val message: String) {
        val success: Boolean get() = ok
    }

    data class FormatOutcome(
        val ok: Boolean,
        val message: String,
        val changedClusters: Long = 0L,
        val bytesWritten: Long = 0L,
    )

    // ------------------------------------------------------------------ layout maths

    /**
     * Regions of the disk that no partition uses, 1 MiB aligned and large enough to hold a real
     * filesystem. The first MiB (and, for GPT, the last one) is always reserved.
     */
    fun freeSpaces(diskSizeBytes: Long, table: PartitionTableInfo): List<FreeSpace> {
        if (diskSizeBytes <= 0) return emptyList()
        val gpt = table.scheme.equals("GPT", ignoreCase = true)
        val diskSectors = diskSizeBytes / SECTOR
        val limit = diskSectors - if (gpt) GPT_RESERVED_SECTORS else 0L
        var cursor = maxOf(ALIGN_SECTORS, if (gpt) GPT_RESERVED_SECTORS else 1L)
        val out = ArrayList<FreeSpace>()
        for (p in table.partitions.sortedBy { it.startLba }) {
            if (p.startLba > cursor) {
                addIfBigEnough(out, cursor, p.startLba - cursor)
            }
            cursor = maxOf(cursor, p.startLba + p.sectorCount)
        }
        if (limit > cursor) addIfBigEnough(out, cursor, limit - cursor)
        return out
    }

    private fun addIfBigEnough(out: MutableList<FreeSpace>, startLba: Long, sectorCount: Long) {
        if (sectorCount * SECTOR < MIN_PARTITION_BYTES) return
        val start = alignUp(startLba)
        val usable = start - startLba
        val count = sectorCount - usable
        if (count * SECTOR < MIN_PARTITION_BYTES) return
        out.add(FreeSpace(start, count))
    }

    fun bestFreeSpace(diskSizeBytes: Long, table: PartitionTableInfo): FreeSpace? =
        freeSpaces(diskSizeBytes, table).maxByOrNull { it.sizeBytes }

    fun alignUp(lba: Long): Long = ((lba + ALIGN_SECTORS - 1) / ALIGN_SECTORS) * ALIGN_SECTORS

    /** Snaps a start to 1 MiB and keeps the size a whole number of MiB (never zero). */
    fun normalise(startLba: Long, sectorCount: Long): Pair<Long, Long> {
        val start = alignUp(startLba)
        val mib = sectorCount / ALIGN_SECTORS
        return if (mib <= 0) start to sectorCount else start to mib * ALIGN_SECTORS
    }

    /**
     * A ready-to-use layout for a blank disk: a small bootable system partition plus one data
     * partition filling the rest. Sizes are clamped so both always fit.
     */
    fun suggestedLayout(diskSizeBytes: Long, scheme: String): List<NewPartition> {
        val gpt = scheme.equals("GPT", ignoreCase = true)
        val diskSectors = diskSizeBytes / SECTOR
        val first = if (gpt) GPT_RESERVED_SECTORS else ALIGN_SECTORS
        val last = diskSectors - if (gpt) GPT_RESERVED_SECTORS else 0L
        val total = last - first
        if (total <= 0) return emptyList()

        val bootSectors = minOf(512L * 1024L, total / 4).coerceAtLeast(ALIGN_SECTORS) // ≤ 256 MiB
        val dataStart = first + bootSectors
        val dataSectors = last - dataStart
        val boot = if (gpt) {
            NewPartition(first, bootSectors, 0xEF, typeGuid = Guid.EFI_SYSTEM, name = "EFI System")
        } else {
            NewPartition(first, bootSectors, 0x0C, bootable = true, name = "BOOT")
        }
        if (dataSectors * SECTOR < MIN_PARTITION_BYTES) return listOf(boot)
        val data = if (gpt) {
            NewPartition(dataStart, dataSectors, 0x83, typeGuid = Guid.MICROSOFT_BASIC_DATA, name = "Data")
        } else {
            NewPartition(dataStart, dataSectors, 0x07, name = "DATA")
        }
        return listOf(boot, data)
    }

    fun typeChoices(scheme: String): List<TypeChoice> = if (scheme.equals("GPT", ignoreCase = true)) {
        listOf(
            TypeChoice(Guid.LINUX_FILESYSTEM, "Linux 文件系统"),
            TypeChoice(Guid.MICROSOFT_BASIC_DATA, "Windows 基本数据 (NTFS)"),
            TypeChoice(Guid.EFI_SYSTEM, "EFI 系统分区 (FAT)"),
            TypeChoice(Guid.BIOS_BOOT, "BIOS 引导分区"),
            TypeChoice(Guid.LINUX_SWAP, "Linux swap"),
        )
    } else {
        listOf(
            TypeChoice("0x83", "Linux"),
            TypeChoice("0x07", "NTFS / exFAT"),
            TypeChoice("0x0C", "FAT32 (LBA)"),
            TypeChoice("0x0B", "FAT32"),
            TypeChoice("0xEF", "EFI 系统分区"),
            TypeChoice("0x82", "Linux swap"),
        )
    }

    // ------------------------------------------------------------------ table writing

    private fun readMbr(image: File): ByteArray? = runCatching {
        Qcow2Image.open(image).use { img -> img.readBytes(0L, SECTOR.toInt()) }
    }.getOrNull()

    /**
     * Replaces the partition table. The MBR boot code and the disk signature are preserved, so
     * editing partitions never destroys a previously installed bootloader.
     */
    fun applyTable(
        image: File,
        scheme: String,
        partitions: List<NewPartition>,
        keepBootCode: Boolean = true,
    ): PartitionResult = runCatching {
        val gpt = scheme.equals("GPT", ignoreCase = true)
        val previous = readMbr(image)
        Qcow2Image.open(image, writable = true).use { img ->
            val diskSectors = img.virtualSize / SECTOR
            val overflow = partitions.any { it.endLba >= diskSectors }
            if (overflow) return PartitionResult(false, "分区超出磁盘范围（磁盘 ${diskSectors} 扇区）")
            if (!gpt && partitions.size > 4) return PartitionResult(false, "MBR 最多支持 4 个主分区")
            if (gpt) {
                val layout = PartitionTables.buildGpt(partitions, diskSectors)
                img.write(0L, layout.protectiveMbr)
                img.write(SECTOR, layout.primaryHeader)
                img.write(layout.primaryEntriesLba * SECTOR, layout.entries)
                img.write(layout.backupEntriesLba * SECTOR, layout.backupEntries)
                img.write(layout.backupHeaderLba * SECTOR, layout.backupHeader)
            } else {
                val signature = previous?.let { mbr ->
                    (mbr[440].toInt() and 0xff) or
                        ((mbr[441].toInt() and 0xff) shl 8) or
                        ((mbr[442].toInt() and 0xff) shl 16) or
                        ((mbr[443].toInt() and 0xff) shl 24)
                } ?: 0
                val mbr = PartitionTables.buildMbr(partitions, signature)
                if (keepBootCode && previous != null) {
                    System.arraycopy(previous, 0, mbr, 0, BOOT_CODE_LENGTH)
                    // Keep the "disk signature present" flag (byte 440..443) consistent.
                    mbr[440] = (signature and 0xff).toByte()
                    mbr[441] = ((signature shr 8) and 0xff).toByte()
                    mbr[442] = ((signature shr 16) and 0xff).toByte()
                    mbr[443] = ((signature shr 24) and 0xff).toByte()
                }
                img.write(0L, mbr)
            }
            img.flush()
        }
        PartitionResult(true, "分区表已写入")
    }.getOrElse { PartitionResult(false, "写入分区表失败：${it.message}") }

    /** Marks one MBR partition as active (bootable) and clears the flag on the others. */
    fun setActive(image: File, partitionIndex: Int): PartitionResult = runCatching {
        val table = EditOps.detectPartitionTable(image)
        if (table == null || table.scheme != "MBR") {
            return PartitionResult(false, "只有 MBR 磁盘需要活动分区标记")
        }
        val mbr = readMbr(image) ?: return PartitionResult(false, "无法读取 MBR")
        for (i in 0 until 4) {
            val off = 446 + i * 16
            mbr[off] = if (i == partitionIndex - 1) 0x80.toByte() else 0x00
        }
        Qcow2Image.open(image, writable = true).use { img ->
            img.write(0L, mbr)
            img.flush()
        }
        PartitionResult(true, "已把分区 $partitionIndex 设为活动分区")
    }.getOrElse { PartitionResult(false, "设置活动分区失败：${it.message}") }

    /** Removes every trace of a partition table (the data stays untouched). */
    fun wipe(image: File): PartitionResult = runCatching {
        val gpt = EditOps.detectPartitionTable(image)?.scheme.equals("GPT", ignoreCase = true)
        Qcow2Image.open(image, writable = true).use { img ->
            img.write(0L, ByteArray(SECTOR.toInt()))
            if (gpt) {
                img.write(SECTOR, ByteArray(SECTOR.toInt()))
                img.write(2 * SECTOR, ByteArray(32 * SECTOR.toInt()))
                val backupEntries = img.virtualSize - 33 * SECTOR
                img.write(backupEntries, ByteArray(32 * SECTOR.toInt()))
                img.write(img.virtualSize - SECTOR, ByteArray(SECTOR.toInt()))
            }
            img.flush()
        }
        PartitionResult(true, "分区表已清除")
    }.getOrElse { PartitionResult(false, "清除分区表失败：${it.message}") }

    fun readBootCode(image: File): ByteArray? = readMbr(image)?.copyOf(BOOT_CODE_LENGTH)

    /**
     * Writes a boot record blob (at most [BOOT_CODE_LENGTH] bytes) into the MBR boot code area
     * while leaving the partition table and the 0x55AA signature exactly as they are.
     *
     * This is the "BIOS 引导" step: with syslinux's `mbr.bin` (or `isohdpfx.bin`, ms-sys, a GRUB
     * stage1 …) written here plus one active partition, the image boots on a BIOS machine.
     */
    fun writeBootCode(image: File, blob: ByteArray, setFirstActive: Boolean = true): PartitionResult = runCatching {
        if (blob.isEmpty()) return PartitionResult(false, "引导代码为空")
        if (blob.size > 512) return PartitionResult(false, "引导代码过大（${blob.size} 字节，最多 512）")
        val mbr = readMbr(image) ?: ByteArray(SECTOR.toInt())
        val code = blob.copyOf(BOOT_CODE_LENGTH)
        System.arraycopy(code, 0, mbr, 0, BOOT_CODE_LENGTH)
        mbr[510] = 0x55
        mbr[511] = 0xAA.toByte()
        if (setFirstActive) {
            val hasActive = (0 until 4).any { mbr[446 + it * 16].toInt() and 0xff == 0x80 }
            if (!hasActive) {
                for (i in 0 until 4) {
                    val off = 446 + i * 16
                    val type = mbr[off + 4].toInt() and 0xff
                    if (type != 0) {
                        mbr[off] = 0x80.toByte()
                        break
                    }
                }
            }
        }
        Qcow2Image.open(image, writable = true).use { img ->
            img.write(0L, mbr)
            img.flush()
        }
        PartitionResult(true, "已写入 BIOS 引导代码（${minOf(blob.size, BOOT_CODE_LENGTH)} 字节）")
    }.getOrElse { PartitionResult(false, "写入引导代码失败：${it.message}") }

    // ------------------------------------------------------------------ filesystems

    /**
     * Creates a fresh filesystem inside [entry] using the light track: the partition is materialised
     * as a **sparse** raw file (old contents are not copied — they are useless when the filesystem is
     * being rebuilt), formatted with the matching mkfs, then only the segments the tool actually
     * wrote are diffed back into the qcow2.
     */
    suspend fun formatPartition(
        context: Context,
        image: File,
        entry: PartitionEntry,
        kind: EditOps.FsKind,
        label: String,
        onProgress: ((Long) -> Unit)? = null,
    ): FormatOutcome {
        val length = entry.sizeBytes
        if (length <= 0) return FormatOutcome(false, "分区大小无效")
        val tmp = File(AppPaths.tmp, "part-${entry.index}-${System.currentTimeMillis()}.raw")
        return try {
            tmp.parentFile?.mkdirs()
            if (!EditOps.createSparseRange(length, tmp)) {
                return FormatOutcome(false, "无法创建临时文件（空间不足？）")
            }
            val snapshot = EditOps.format(context, kind, tmp, label)
            if (!snapshot.success) {
                return FormatOutcome(false, "mkfs 失败：${snapshot.summary}")
            }
            val rebuild = EditOps.writeBackRebuilt(image, entry.startByte, length, tmp, onProgress)
            val written = rebuild.result
            FormatOutcome(
                ok = true,
                message = "${kind.label} 已写入分区 ${entry.index}（改变 ${written.changedClusters} 个簇，" +
                    if (rebuild.sparse) {
                        "稀疏回写 ${Fmt.size(rebuild.dataBytes)}）"
                    } else {
                        "完整差分回写）"
                    },
                changedClusters = written.changedClusters,
                bytesWritten = written.bytesWritten,
            )
        } catch (t: Throwable) {
            FormatOutcome(false, "格式化失败：${t.message}")
        } finally {
            tmp.delete()
        }
    }
}